### PR TITLE
Complete profile fixes

### LINKED ISSUE #164: Add tags duplicate check

### LINKED ISSUE #165: On complete profile add checks
- [x] Check bio lenght (at least x chars)
- [x] Check at least 3 tags
- [ ] At least 1 picture
- [x] 18+

### PR DESCRIPTION
**Pull request by Seluj78**
Closes #164 
Closes #165

### CODE REVIEW

File: frontend/src/pages/home.js [hunk 1]
```diff
@@ -3,12 +3,7 @@ import { useHistory } from 'react-router-dom';
 import useFetchData from '../hooks/fetch_data';
 import Loading from '../components/loading';
 import Error from '../components/error';
-
-const logOut = history => () => {
-	localStorage.removeItem("refresh_token");
-	sessionStorage.removeItem("access_token");
-	history.push('login');
-}
+import { apiCall, deleteRefresh, logOut } from "../utils"
```
Comment (gmorer) [inline frontend/src/pages/home.js:6]:
```suggestion
import { logOut } from "../utils"
```
