### PR TITLE
Recommendations + Search

### LINKED ISSUE #302: Speedup/redo the recommendations process

### LINKED ISSUE #323: Celery worker option error in docker compose
workers       | Usage: celery worker [OPTIONS]
workers       | Try 'celery worker --help' for help.
workers       |
workers       | Error: no such option: --workdir

### PR DESCRIPTION
**Pull request by supalarry**
Closes #302
Closes #323

### CODE REVIEW

File: frontend/src/views/app/Search.vue [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+            'swimming', 'wine', 'reading', 'foodie', 'netflix', 'music', 'yoga', 'golf',
+            'photography', 'baking', 'shopping', 'outdoors', 'art', 'travel', 'hiking',
+            'running', 'volunteering', 'cycling', 'climbing', 'tea', 'fishing', 'soccer',
+            'museum', 'dancing', 'surfing', 'karaoke', 'parties', 'diy',
+            'walking', 'cat lover', 'movies', 'gardening', 'trivia', 'working out',
+            'cooking', 'gamer', 'brunch', 'blogging', 'picknicking', 'athlete',
+            'dog lover', 'politics', 'environmentalism', 'instagram', 'spirituality',
+            'language exchange', 'sports', 'comedy', 'fashion', 'disney', 'vlogging',
+            'astrology', 'board games', 'craft beer', 'coffee', 'writer',
+          ]"
```
Comment (Seluj78) [inline frontend/src/views/app/Search.vue:36]: Should I add a route that serves the list of tags ? So we can modify it easily if needed in the backend and your frontend can just get a public list of tags

**Review by Seluj78 — CHANGES_REQUESTED** [review]

**Review by Seluj78 — APPROVED** [review]
